spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1003813169554-ib4dafd6hta21k7fvj2spojslrepvsuk.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
paypal:
  mode: sandbox
  baseUrl: https://api-m.sandbox.paypal.com
  clientId: Af7FgUoed-2LVViOhZkm8YL1iwNX8-JHU70pskX963UNcQEzYu4H8XSAY17kjHdjYYEGG6j26HBZ9x7Q
  secret: EAJBsraxuzmCe4Rb3ekYfJMQyPWhYNFHfzRTxHMwlsDjR8V9r35YQZlaaCJkave4gh3fgNq5oIYg11Nv